# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.6

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

install:
  - pip install .
  - pip install -r requirements-test.txt
  - pip install -U coverage codecov

# command to run tests, e.g. python setup.py test
script:
  - python -m coverage run --source pyppeteer -m unittest discover pyppeteer 
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then && codecov; fi
