# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.6

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements-test.txt
  - pip install coverage codecov tox

# command to run tests, e.g. python setup.py test
script:
  - tox

after_success:
  - python -m coverage run --source pyppeteer -m unittest discover tests && coverage report && codecov -b $TRAVIS_BRANCH
