# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: false
dist: trusty

language: python
matrix:
  include:
    - python: "3.5"
      env: TOXENV="py35"
    - python: "3.6"
      env: TOXENV="py36,doit,codecov"
    - python: "3.7-dev"
      env: TOXENV="py37"

install:
  - pip install tox

script:
  - tox
